package blocks;

public class MainRunner {
    public static void main(String[] args) {
        ClassA classA = new ClassA();
        System.out.println("-----------");
        ClassB classB= new ClassB();
    }
//    Cikti
//    ClassA Static Blok Cagrildi...
//    ClassA Instance Blok Cagrildi...
//    ClassA Constructor Cagrildi...
//            -----------
//    ClassB Static Blok Cagrildi...
//    ClassA Instance Blok Cagrildi...
//    ClassA Constructor Cagrildi...
//    ClassB Instance Blok Cagrildi...
//    ClassB Constructor Cagrildi...
//
}
